apiVersion: helm.toolkit.fluxcd.io/v2
kind: ClastixParams
metadata:
  name: soris-stage
  annotations:
    git-version: 2.0.1
spec:
  contract: "CNT.19.0035.01"
  clustername: soris-stage
  clusterdomain: soris-stage.local
  apiserverip: 10.19.27.61
  cpreplicas: 3
  datastore: etcd-datastore
  k8sversion: 1.32
  gatewayip: 10.119.1.254

  dcname: EDA - Datacenter Elogic A - Produzione
  dcurl: 10.19.6.1
  dcthumbprint: 2D:91:19:B3:27:30:02:CE:C0:38:CF:77:EF:1B:E6:A8:4B:9C:BB:D6:C5:59:DD:6B:6C:DF:F2:65:83:24:C1:96
  dccredsecret: vsphere-cluster-identity
  dcfolder: "folder"
  dcnodepool: 
  dcstorage: 
  dcvmtemplate: 
  dcnetwork: 

  profilelabels:
    - fortigate:fabric

  ipampool: 

    - rangestart: 192.168.3.10
      rangeend: 192.168.3.100
      prefix: 26
      gateway: 192.168.3.254
      ipamname: 26

  nodesinfo:
    - nodename: 25
      replicas: 2
      cpu: 2
      mbram: 4096
      gbdisk: 150
      nodetaints:
  # -- Labels to add to the node pool when joining the cluster
      nodelabels:
        - labelkey: k
          labelvalue: v
